[[customizations.user]]
name = "user"
password = "123456"
groups = ["wheel"]

[[customizations.filesystem]]
mountpoint = "/boot"
size = 209715200

[customizations.kernel]
append = "root=PARTLABEL=userdata ostree.prepare-root.composefs=0 selinux=0"
