name: mipad5 fedora+lineage dualboot
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: pocketblue/actions/partition-images@main
        with:
          config_file: ./config.toml
          esp_size: 536870912
          rootfs: ext4
          registry: ${{ vars.REGISTRY }}
          image_name: mipad5-gnome-desktop
          image_tag: 42
      - name: dependencies
        run: |
          curl -L https://7-zip.org/a/7z2501-linux-arm64.tar.xz | tar -xJf -
          sudo cp 7zzs /bin/7z
      - name: building mipad5 common
        run: |
          bash common/build.sh
      - name: building mipad5 second step
        run: |
          bash mipad5/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: mipad5_fedora_lineage_dualboot
          path: mipad5_fedora_lineage_dualboot.7z
