name: oneplus6 fedora+lineage dualboot
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: pocketblue/actions/partition-images@main
        with:
          config_file: ./config.toml
          esp_size: 268435456
          rootfs: ext4
          registry: ${{ vars.REGISTRY }}
          image_name: oneplus6-gnome-mobile
          image_tag: 42
      - name: dependencies
        run: |
          curl -L https://github.com/ssut/payload-dumper-go/releases/download/1.3.0/payload-dumper-go_1.3.0_linux_arm64.tar.gz | tar -xzf -
          curl -L https://7-zip.org/a/7z2501-linux-arm64.tar.xz | tar -xJf -
          sudo cp 7zzs /bin/7z
          sudo cp payload-dumper-go /bin/payload-dumper-go
      - name: oneplus6 common
        run: |
          bash common/build.sh
      - name: oneplus6 enchilada
        env:
          model: oneplus6
          codename: enchilada
          twrp: 3.7.0_11-0
          lineage_build: 20250924
        run: |
          bash oneplus6/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: oneplus6_enchilada_fedora_lineage_dualboot
          path: build/oneplus6_enchilada_fedora_lineage_dualboot.7z
      - name: oneplus6t fajita
        env:
          model: oneplus6t
          codename: fajita
          twrp: 3.7.0_9-0
          lineage_build: 20250923
        run: |
          bash oneplus6/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: oneplus6t_fajita_fedora_lineage_dualboot
          path: build/oneplus6t_fajita_fedora_lineage_dualboot.7z
