name: xiaomi-nabu-flashable
run-name: Xiaomi Pad 5
on:
  workflow_dispatch: {}

jobs:
  refind:
    uses: ./.github/workflows/xiaomi-nabu-refind.yml

  reboot2android:
    uses: ./.github/workflows/xiaomi-nabu-reboot2android.yml

  flashable:
    needs: [refind, reboot2android]
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
      
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: dualboot

      - name: Installing files
        run: |
          mkdir -p flashable/META-INF/com/google/android/
          cp dualboot/devices/xiaomi-nabu/update-binary flashable/META-INF/com/google/android
          echo "# empty" > flashable/META-INF/com/google/android/updater-script
          
          cp reboot2android flashable/android -r
          cp refind/refind flashable/BOOT -r
          mv flashable/BOOT/refind_aa64.efi flashable/BOOT/BOOTAA64.EFI

      - name: Making zip
        run: |
          cd flashable
          zip -r ../flashable.zip META-INF android BOOT

      - name: Artifact
        uses: actions/upload-artifact@v7
        with:
          name: flashable
          path: flashable.zip

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: Xiaomi Pad 5 Flashable
          files: flashable.zip
          draft: true
